---
title: "Map_making"
author: "Erica Robertson"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This goal of this markdown is to run through multiple ways to make maps. We'll start with taking a typical raster file and plotting it with ggplot. Then we'll talk about adding points, such as sampling locations, to that layer. I'll go over different places to get different types of data, including built in packages in R such as rnaturalearth. Then I'll do a short session at the end for working with ebird trend data specifically: range maps, abundance maps, etc.

This doesn't replace taking a course in visualizing spatial data in R, but should be a jumping off point for making basic maps to include in proposals for research and whatnot. I'm also not going into the details of ggplot because, although I am proficient, there are far better resources outthere for specifics. Holden will also likely have his own ways of doing things, so I invite him to add in subsections with alternative approaches. Finally, I do almost all of my plotting with ggplot. Plotting with base R is also an option, and in some cases can be the better options, but I won't go over that here as I'm not good at it!

# Getting mapping data
There are ton's of places to find rasters online.




